routes/web.php
<?php

use App\Models\Penjual;
use App\Models\KoleksiCupang;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\GalleryController;
use App\Http\Controllers\PenjualController;
use App\Http\Controllers\KoleksiCupangController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::middleware(['auth'])->group(function () {
    Route::get('/home',[HomeController::class, 'index'])->name('home.index');

    Route::get('/koleksicupang/cari',[KoleksiCupangController::class, 'search'])->name('koleksicupang.search');
    Route::get('/penjual/cari',[PenjualController::class, 'search'])->name('penjual.search');
    Route::resource('/gallery', GalleryController::class);
    Route::resource('/koleksicupang', KoleksiCupangController::class);
    Route::resource('/penjual', PenjualController::class);
});

resources/views/pages/koleksi/create.blade.php
@extends('layouts.app')
@section('content')
    <div class="page-inner">
        <div class="page-header">
            <h4 class="page-title">Data Koleksi</h4>
        </div>
        <div class="row">
            <div class="col-md-12">
                @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
                <div class="card">
                    <div class="card-header">
                        <div class="card-title">Tambah Data</div>
                    </div>
                    <div class="card-body">
                        <form action="{{ route('koleksicupang.store') }}" method="POST" enctype="multipart/form-data">
                            @csrf
                            <div class="form-group">
                                <label for="nama_cupang">Nama Cupang</label>
                                <input type="text" class="form-control" name="nama_cupang" id="nama_cupang"
                                    placeholder="Masukkan Nama cupang..." required>
                            </div>

                            <div class="form-group">
                                <label for="jenis_cupang">Jenis Cupang</label>
                                <input type="text" class="form-control" name="jenis_cupang" id="jenis_cupang"
                                    placeholder="Masukkan Jenis cupang..." required>
                            </div>

                            <div class="form-group">
                                <label for="image">Gambar</label>
                                <input type="file" class="form-control-file" id="image" name="image" required>
                            </div>

                            <div class="form-group">
                                <label for="harga">Harga</label>
                                <input type="number" class="form-control" name="harga" id="harga"
                                    placeholder="Masukkan Harga..." required>
                            </div>

                            <div class="form-group">
                                <label for="penjual_id">Penjual</label>
                                <select name="penjual_id" id="penjual_id" required class="form-control">
                                    <option value disable>Pilih Penjual</option>
                                    @foreach ($penjual as $item)
                                        <option value="{{ $item->id }}">{{ $item->nama_penjual }}</option>
                                    @endforeach
                                </select>
                            </div>

                            <div class="form-group">
                                <label for="tanggal_beli">Tanggal Beli</label>
                                <input type="date" class="form-control" name="tanggal_beli" id="tanggal_beli" required>
                            </div>

                            <div class="form-group">
                                <label for="deskripsi">Deskripsi</label>
                                <textarea class="form-control" id="deskripsi" name="deskripsi" rows="3"
                                    placeholder="Masukkan Deskripsi Cupang..." required></textarea>
                            </div>

                            <button type="submit" class="btn btn-primary">Save changes</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/pages/koleksi/edit.blade.php
@extends('layouts.app')
@section('content')
    <div class="page-inner">
        <div class="page-header">
            <h4 class="page-title">Data Master</h4>
        </div>
        <div class="row">
            <div class="col-md-12">
                @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
                <div class="card">
                    <div class="card-header">
                        <div class="card-title">Card Header</div>
                    </div>
                    <div class="card-body">
                        <form action="{{ route('koleksicupang.update', $koleksi->id) }}" method="POST" enctype="multipart/form-data">
                            @csrf
                            @method('PUT')
                            <div class="form-group">
                                <label for="nama_cupang">Nama Cupang</label>
                                <input type="text" class="form-control" name="nama_cupang" id="nama_cupang"
                                    placeholder="Masukkan Nama cupang..." value="{{ $koleksi->nama_cupang }}">
                            </div>
                    
                            <div class="form-group">
                                <label for="jenis_cupang">Jenis Cupang</label>
                                <input type="text" class="form-control" name="jenis_cupang" id="jenis_cupang"
                                    placeholder="Masukkan Jenis cupang..." value="{{ $koleksi->jenis_cupang }}">
                            </div>
                    
                            <div class="form-group">
                                <label for="image">Gambar</label>
                                <input type="file" class="form-control-file" id="image" name="image">
                            </div>
                    
                            <div class="form-group">
                                <label for="harga">Harga</label>
                                <input type="number" class="form-control" name="harga" id="harga" value="{{ $koleksi->harga }}">
                            </div>
                    
                            <div class="form-group">
                                <label for="penjual_id">Penjual</label>
                                <select name="penjual_id" id="penjual_id" required class="form-control">
                                     <option value={{ $koleksi->penjual_id }}>{{ $koleksi->penjual->nama_penjual }}</option>
                                     @foreach ($penjual as $item)
                                         <option value="{{ $item->id }}">{{ $item->nama_penjual }}</option>
                                     @endforeach
                                </select>
                            </div>
                    
                            <div class="form-group">
                                <label for="tanggal_beli">Tanggal Beli</label>
                                <input type="date" class="form-control" name="tanggal_beli" id="tanggal_beli" value="{{ $koleksi->tanggal_beli }}">
                            </div>
                    
                            <div class="form-group">
                                <label for="deskripsi">Deskripsi</label>
                                <textarea class="form-control" id="deskripsi" name="deskripsi" rows="3">{{ $koleksi->deskripsi }}</textarea>
                            </div>
                    
                            <button type="submit" class="btn btn-primary">Simpan Data</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/pages/koleksi/index.blade.php
@extends('layouts.app')
@section('content')
    <div class="page-inner">
        <div class="page-header">
            <h4 class="page-title">Data Cupang</h4>
        </div>
        <div class="row mb-3">
            <div class="col-md-4">
                <a href="{{ route('koleksicupang.create') }}" class="btn btn-md btn-primary">
                    + Data Cupang
                </a>
            </div>
            <div class="col-md-8 form-inline justify-content-end">
                <form action="{{ route('koleksicupang.search') }}" method="GET">
                    <input type="text" class="form-control" name="keyword" placeholder="Cari Cupang .." value="">
                    <input type="submit" class="btn btn-secondary" value="Search">
                </form>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <div class="card-title">Data Cupang</div>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive mt-2"> 
                            <table class="table table-bordered">
                                <thead>
                                    <tr>
                                        <th scope="col">#</th>
                                        <th scope="col">Nama Cupang</th>
                                        <th scope="col">Jenis Cupang</th>
                                        <th scope="col">Gambar</th>
                                        <th scope="col">Harga</th>
                                        <th scope="col">Penjual</th>
                                        <th scope="col">Tanggal Beli</th>
                                        <th scope="col">Deskripsi</th>
                                        <th scope="col">Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @forelse ($koleksi as $item)
                                        <tr>
                                            <th scope="row">{{ ++$i }}</th>
                                            <td>{{ $item->nama_cupang }}</td>
                                            <td>{{ $item->jenis_cupang }}</td>
                                            <td><img src="{{ Storage::url('assets/image/'.$item->image) }}" alt="image" width="150px"
                                                    class="img-fluid"></td>
                                            <td>{{ $item->harga }}</td>
                                            <td>{{ $item->penjual->nama_penjual }}</td>
                                            <td>{{ $item->tanggal_beli }}</td>
                                            <td>{{ Str::limit($item->deskripsi, 25) }}</td>
                                            <td>
                                                <a href="{{ route('koleksicupang.edit', $item->id) }}" class="btn btn-info btn-sm mt-2 mb-2"><i
                                                        class="fas fa-pencil-alt"></i></a>
                                                <form action="{{ route('koleksicupang.destroy', $item->id) }}" method="POST" class="d-inline">
                                                    @csrf
                                                    @method('DELETE')
                                                    <button class="btn btn-danger btn-sm mb-2" onclick="return confirm('Hapus data?')">
                                                        <i class="fa fa-trash"></i>
                                                    </button>
                                                </form>
                                            </td>
                                        </tr>
                                    @empty
                                    <tr>
                                        <td colspan="9" class="text-center">
                                            Tidak Ada Data
                                        </td>
                                    </tr>
                                    @endforelse
                                </tbody>
                            </table>
                                {{ $koleksi->links() }}
                            </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
@endsection