routes/web.php
<?php

use App\Models\Penjual;
use App\Models\KoleksiCupang;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\GalleryController;
use App\Http\Controllers\PenjualController;
use App\Http\Controllers\KoleksiCupangController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::middleware(['auth'])->group(function () {
    Route::get('/home',[HomeController::class, 'index'])->name('home.index');

    Route::get('/koleksicupang/cari',[KoleksiCupangController::class, 'search'])->name('koleksicupang.search');
    Route::get('/penjual/cari',[PenjualController::class, 'search'])->name('penjual.search');
    Route::resource('/gallery', GalleryController::class);
    Route::resource('/koleksicupang', KoleksiCupangController::class);
    Route::resource('/penjual', PenjualController::class);
});

app/Models/Penjual.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Penjual extends Model
{
    use HasFactory;

    protected $table = 'penjual';
    protected $guarded = [];

    public function cupang(){
        return $this->hasMany('App\Models\KoleksiCupang');
    }
}

app/Http/Controllers/Api/PenjualController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Models\Penjual;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Validator;

class PenjualController extends Controller
{
    public function index()
    {
        $penjual = Penjual::where('users_id', Auth::user()->id)->get();
        return response()->json([
            'success' => true,
            'message' => 'List Semua Cupang',
            'data' => $penjual,
        ], 200);
    }

    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'nama_penjual' => 'required',
            'no_telp' => 'required|min:10',
            'email' => 'required|email',
            'alamat' => 'required|min:5',
        ]);

        if ($validator->fails()) {
            return response()->json([
                'success' => false,
                'message' => 'Semua Kolom Wajib Diisi!',
                'data' => $validator->errors(),
            ], 401);
        } else {
            $penjual = Penjual::create([
                'nama_penjual' => $request->input('nama_penjual'),
                'no_telp' => $request->input('no_telp'),
                'email' => $request->input('email'),
                'alamat' => $request->input('alamat'),
                'users_id' => Auth::user()->id,
            ]);

            if ($penjual) {
                return response()->json([
                    'success' => true,
                    'message' => 'Penjual Berhasil Disimpan!',
                    'data' => $penjual,
                ], 201);
            } else {
                return response()->json([
                    'success' => false,
                    'message' => 'Penjual Gagal Disimpan!',
                ], 400);
            }
        }
    }

    public function show($id)
    {
        $penjual = Penjual::find($id);

        if ($penjual) {
            return response()->json([
                'success' => true,
                'message' => 'Detail Penjual!',
                'data' => $penjual,
            ], 200);
        } else {
            return response()->json([
                'success' => false,
                'message' => 'Penjual Tidak Ditemukan!',
            ], 404);
        }
    }

    public function update(Request $request, $id)
    {
        $validator = Validator::make($request->all(), [
            'nama_penjual' => 'required',
            'no_telp' => 'required|min:10',
            'email' => 'required|email',
            'alamat' => 'required|min:5',
        ]);

        if ($validator->fails()) {
            return response()->json([
                'success' => false,
                'message' => 'Semua Kolom Wajib Diisi!',
                'data' => $validator->errors(),
            ], 401);
        } else {
            $penjual = Penjual::whereId($id)->update([
                'nama_penjual' => $request->input('nama_penjual'),
                'no_telp' => $request->input('no_telp'),
                'email' => $request->input('email'),
                'alamat' => $request->input('alamat'),
                'users_id' => Auth::user()->id,
            ]);

            if ($penjual) {
                return response()->json([
                    'success' => true,
                    'message' => 'Penjual Berhasil Diupdate!',
                    'data' => $penjual,
                ], 201);
            } else {
                return response()->json([
                    'success' => false,
                    'message' => 'Penjual Gagal Diupdate!',
                ], 400);
            }

        }
    }

    public function destroy($id)
    {
        $penjual = Penjual::whereId($id)->first();
        $penjual->delete();

        if ($penjual) {
            return response()->json([
                'success' => true,
                'message' => 'Penjual Berhasil Dihapus!',
            ], 200);
        }
    }
}

app/Http/Controllers/PenjualController.php
<?php

namespace App\Http\Controllers;

use App\Models\Penjual;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Http\Requests\PenjualRequest;
use App\Models\KoleksiCupang;

class PenjualController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $penjual = Penjual::where('users_id', Auth::user()->id)->orderBy('id','DESC')->paginate(5);
        return view('pages.penjual.index', compact('penjual'))->with('i',(request()->input('page', 1) - 1) * 5);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('pages.penjual.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(PenjualRequest $request)
    {
        $data = $request->all();
        $data['users_id'] = Auth::user()->id;
        Penjual::create($data);
        
        return redirect()->route('penjual.index')->with('toast_success', 'Data berhasil disimpan');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $penjual = Penjual::findorFail($id);
        return view('pages.penjual.edit', compact('penjual'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(PenjualRequest $request, $id)
    {
        $data = $request->all();
        $item =  Penjual::findorFail($id);
        $item->update($data);

        return redirect()->route('penjual.index')->with('toast_success', 'Data berhasil diubah');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $data = Penjual::findorFail($id);
        $data->delete();

        return redirect()->route('penjual.index')->with('toast_success', 'Data berhasil dihapus');
    }

    public function search(Request $request)
    {
		$keyword = $request->keyword;
        $penjual = Penjual::where('nama_penjual','like',"%".$keyword."%")->paginate(5);

        return view('pages.penjual.index', compact('penjual'))->with('i',(request()->input('page', 1) - 1) * 5);
    }
}

resources/views/pages/penjual/create.blade.php
@extends('layouts.app')
@section('content')
    <div class="page-inner">
        <div class="page-header">
            <h4 class="page-title">Data Penjual</h4>
        </div>
        <div class="row">
            <div class="col-md-12">
                @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
                <div class="card">
                    <div class="card-header">
                        <div class="card-title">Tambah Data</div>
                    </div>
                    <div class="card-body">
                        <form action="{{ route('penjual.store') }}" method="POST">
                            @csrf
                            <div class="form-group">
                                <label for="nama_penjual">Nama Penjual</label>
                                <input type="text" class="form-control" name="nama_penjual" id="nama_penjual"
                                    placeholder="Masukkan Nama Penjual..." required>
                            </div>
                    
                            <div class="form-group">
                                <label for="no_telp">No Telp</label>
                                <input type="number" class="form-control" name="no_telp" id="no_telp"
                                    placeholder="Masukkan No Telp..." required>
                            </div>
                    
                            <div class="form-group">
                                <label for="email">Email</label>
                                <input type="email" class="form-control" id="email" name="email" placeholder="Masukkan Email" required>
                            </div>
                    
                            <div class="form-group">
                                <label for="alamat">Alamat</label>
                                <textarea class="form-control" id="alamat" name="alamat" rows="3"
                                    placeholder="Masukkan Alamat Penjual..." required></textarea>
                            </div>
                    
                            <button type="submit" class="btn btn-primary">Save changes</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/pages/penjual/edit.blade.php
@extends('layouts.app')
@section('content')
    <div class="page-inner">
        <div class="page-header">
            <h4 class="page-title">Data Penjual</h4>
        </div>
        <div class="row">
            <div class="col-md-12">
                @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
                <div class="card">
                    <div class="card-header">
                        <div class="card-title">Tambah Data</div>
                    </div>
                    <div class="card-body">
                        <form action="{{ route('penjual.update', $penjual->id) }}" method="POST">
                            @csrf
                            @method('PUT')
                            <div class="form-group">
                                <label for="nama_penjual">Nama Penjual</label>
                                <input type="text" class="form-control" name="nama_penjual" id="nama_penjual"
                                    placeholder="Masukkan Nama Penjual..." value="{{ $penjual->nama_penjual }}">
                            </div>
                    
                            <div class="form-group">
                                <label for="no_telp">No Telp</label>
                                <input type="number" class="form-control" name="no_telp" id="no_telp"
                                    placeholder="Masukkan No Telp..." value="{{ $penjual->no_telp }}">
                            </div>
                    
                            <div class="form-group">
                                <label for="email">Email</label>
                                <input type="email" class="form-control" id="email" name="email" placeholder="Masukkan Email" value="{{ $penjual->email }}">
                            </div>
                    
                            <div class="form-group">
                                <label for="alamat">Alamat</label>
                                <textarea class="form-control" id="alamat" name="alamat" rows="3"
                                    placeholder="Masukkan Alamat Penjual..." required>{{ $penjual->alamat }}</textarea>
                            </div>
                    
                            <button type="submit" class="btn btn-primary">Save changes</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/pages/penjual/index.blade.php
@extends('layouts.app')
@section('content')
    <div class="page-inner">
        <div class="page-header">
            <h4 class="page-title">Data Penjual</h4>
        </div>
        <div class="row mb-3">
            <div class="col-md-4">
                <a href="{{ route('penjual.create') }}" class="btn btn-md btn-primary">
                    + Data Penjual
                </a>
            </div>
            <div class="col-md-8 form-inline justify-content-end">
                <form action="{{ route('penjual.search') }}" method="GET">
                    <input type="text" class="form-control" name="keyword" placeholder="Cari Penjual .." value="">
                    <input type="submit" class="btn btn-secondary" value="Search">
                </form>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <div class="card-title">Data Penjual</div>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive mt-2"> 
                            <table class="table table-bordered">
                                <thead>
                                    <tr>
                                        <th scope="col">#</th>
                                        <th scope="col">Nama Penjual</th>
                                        <th scope="col">No Telp</th>
                                        <th scope="col">Email</th>
                                        <th scope="col">Alamat</th>
                                        <th scope="col">Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @forelse ($penjual as $item)
                                        <tr>
                                            <th scope="row">{{ ++$i }}</th>
                                            <td>{{ $item->nama_penjual }}</td>
                                            <td>{{ $item->no_telp }}</td>
                                            <td>{{ $item->email }}</td>
                                            <td>{{ $item->alamat }}</td>
                                            <td>
                                                <a href="{{ route('penjual.edit', $item->id) }}" class="btn btn-info btn-sm"><i
                                                        class="fas fa-pencil-alt"></i></a>
                                                        <form action="{{ route('penjual.destroy', $item->id) }}" method="POST" class="d-inline">
                                                            @csrf
                                                            @method('DELETE')
                                                            <button class="btn btn-danger btn-sm" onclick="return confirm('Hapus data?')">
                                                                <i class="fa fa-trash"></i>
                                                            </button>
                                                        </form>
                                            </td>
                                        </tr>
                                    @empty
                                    <tr>
                                        <td colspan="9" class="text-center">
                                            Tidak Ada Data
                                        </td>
                                    </tr>
                                    @endforelse
                                </tbody>
                            </table>
                        
                            </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
@endsection